volumes:
  postgres_data:

networks:
  github-subscriptions:
    name: subscriptions

services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      github-subscriptions:
        aliases:
          - postgres
    env_file:
      - deploy/postgres/.env.postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 1s
      timeout: 1s
      retries: 20

  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    expose:
      - '${SERVER_PORT}'
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      github-subscriptions:
        aliases:
          - backend